### ISSUE TITLE
Support for a free plan

### ISSUE THREAD

**Issue by dulacp** [cypreess/django-plans#24]
It appears that there is not a real support for a free plan.
The spec is something like this for me

---
### Spec
- there can only be one free plan (mutiple free plans it doesn't make sense)
- a free plan doesn't have an expiration date
- when the new user grace period ended it falls back to a free default plan if one exists and if quota validations passed

---

I'm willing to contribute to this one, just want to discuss the specificities with you a little bit, because I'm sure you've already thought about it.

**Comment by Hedayet** [comment]
FIxed now?
