### ISSUE TITLE
Support for Django 1.6 and 1.7

### ISSUE THREAD

**Issue by kevwilde** [cypreess/django-plans#47]
Currently updating some models to match the new 1.6 requirements (with deprecations scheduled in 1.8) in https://github.com/kevwilde/django-plans/tree/django1.7support

Waiting for a new release of ordered_models (see https://github.com/bfirsh/django-ordered-model/issues/41) before creating a pull request.

**Comment by ierror** [comment]
any progress here?

**Comment by vaibhav-jain** [comment]
Any progress ??

**Comment by Alir3z4** [comment]
This is fixed in #56
