### ISSUE TITLE
Is this package maintained anymore ?

### ISSUE THREAD

**Issue by Alir3z4** [cypreess/django-plans#57]
Looking at the pull requests and issues being left, i wonder if this project is not mmaintained anymore.

In a project of mine, I need the exact mind functionality, however the package seems to be abandoned.

@cypreess could you please let me know if I can take over the maintainership under @SavandBros, my account or even a new org ?

**Comment by cypreess** [comment]
Hey @Alir3z4, I was hoping to get back to django-plans to clean up a little bit all incoming pull requests but sadly said I don't have a time for that anymore, and I stopped needed this project personally so my motivation to do that is currently low. I would love to see some experience maintainers so I am happy to join you into maintainers into this repo. 

Feel free to act actively on this project.

**Comment by Alir3z4** [comment]
@cypreess Thank you for your quick response and giving me maintainership access.

I will be needing this package for a project of mine and surely I'd heavily need this.
I can work on the pull requests and issues and get the repo up dated for future enhancements.

I'll go ahead and get some of the pull requested cleaned up and merge them into master.

**Comment by cypreess** [comment]
Good luck @Alir3z4!

**Comment by cypreess** [comment]
PS. Ping me later when you will be able to issue a new PyPi package.

**Comment by Alir3z4** [comment]
@cypreess The pypi package for the django-plans is already taken at https://pypi.python.org/pypi/django-plans

It would be great if the pypi maintainer could release the package name so we could push this repo there.

@swappsco or @cdvv7788 if you would release the pypi name so we could do that.
