### ISSUE TITLE
Compatiblity with django2.0

### ISSUE THREAD

**Issue by cypreess** [cypreess/django-plans#63]
I think within the new version of django-plans we should bring compatibility with dj2.0 and drop support for python2.x

**Comment by afidegnum** [comment]
is it compatible to django 2?

**Comment by cypreess** [comment]
Not yet - at least nobody tested. Pull requests are welcome.

**Comment by Alir3z4** [comment]
Fixed in https://github.com/cypreess/django-plans/pull/67
